repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.6
    hooks:
      - id: clang-format
        exclude_types: [javascript, json]
        args: ["-i", "--style=file"]
  - repo: https://github.com/psf/black
    rev: 25.11.0 
    hooks:
      - id: black
        args: ["--line-length=100", "--exclude=z2r_accel/_core/build"]
