[build-system]
requires = ["setuptools", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "paulicpp"
version = "0.1.0"
description = "projet"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pybind11",
]


[project.optional-dependencies]
dev = [
    "pytest",
    "mypy",
]
test = [
    "pytest",
    "numpy",
]


[tool.setuptools]
packages = ["voidops", "paulicpp"]

[tool.setuptools.package-data]
"*" = ["*.so", "*.pyi"]

[tool.setuptools.package-dir]
"" = "."